import { AuthProvider } from "@/context/AuthContext";
import QueryProvider from "@/Providers/QueryClientProvider ";

import { CartProvider } from "@/context/CartContext";
import { ModalProvider } from "@/context/ModalContext";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ModalProvider>
            <AuthProvider>
              <CartProvider>
           
                {children}
          
              </CartProvider>
            </AuthProvider>
          </ModalProvider>
        </QueryProvider>

        <Toaster />
      </body>
    </html>
  );
}
